=== sleod/tas-framework-lite/src/main/resources/schema/TestCaseJsonSchema.json
{
  "id": "https://www.qa.ch/testautomation/testcase/schema#",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "RCH Test Framework - Test Case Schema",
  "type": "object",
  "properties": {
    "meta": {
      "type": "array",
      "description": "Meta Filter for Test Case Selection",
      "items": {
        "uniqueItems": true,
        "type": "string"
      }
    },
    "name": {
      "type": "string",
      "description": "Test Case Name. Validated with folder name pattern.",
      "pattern": "^[^\\s^\\x00-\\x1f\\\\?*:\"\";<>|\\/.][^\\x00-\\x1f\\\\?*:\"\";<>|\\/]*[^\\s^\\x00-\\x1f\\\\?*:\"\";<>|\\/.]+$"
    },
    "type": {
      "type": "string",
      "description": "Test Case Type, the test driver depends on the type",
      "enum": [
        "app",
        "web_app",
        "web_app_remote",
        "mobile_app",
        "mobile_web_app",
        "mobile_ios",
        "mobile_android",
        "rest"
      ]
    },
    "description": {
      "type": "string",
      "description": "Test Case Description"
    },
    "source": {
      "type": "string",
      "description": "where the test case originally stored.",
      "enum": [
        "TFS",
        "AzureDevOps",
        "JIRA"
      ]
    },
    "testCaseId": {
      "type": "string",
      "description": "Test Case ID, reference to external manual test case that storage in test case management system like QC, JIRA..."
    },
    "testCaseIdMap": {
      "type": "object",
      "description": "(mobile_app only) Test Case ID Map with key for platform of device, reference to external manual test case that storage in test case management system like QC, JIRA...",
      "examples": [
        {
          "iOS": "id1",
          "Android": "id2"
        }
      ]
    },
    "requirement": {
      "type": "string",
      "description": "Requirement reference similar to test case id"
    },
    "reference": {
      "type": "string",
      "description": "External extra Reference, optional information"
    },
    "screenshotLevel": {
      "type": "string",
      "enum": [
        "ERROR",
        "SUCCESS"
      ],
      "description": "screen shot will be taken on given level"
    },
    "testDataRef": {
      "type": "string",
      "examples": [
        "File:MyData.json",
        "File:testData/AT/multiCase.csv",
        "SQL:testData/AT/SQLs/mySQL.sql"
      ],
      "description": "Test Data Reference, File, sql statement or also DB interface."
    },
    "additionalTestDataFile": {
      "type": "string",
      "description": "Test Data Reference, json file only.",
      "examples": [
        "File:testData/MyData.json"
      ]
    },
    "appName": {
      "type": "string",
      "description": "Name Display of iOS app for mobile testing.",
      "examples": [
        "xxx.xxxx.google..."
      ]
    },
    "appPackage": {
      "type": "string",
      "description": "(Android only) Start point of Android app for mobile testing.",
      "examples": [
        "xxx.xxxx.google..."
      ]
    },
    "bundleId": {
      "type": "string",
      "description": "Bundle ID for iOS mobile testing.",
      "examples": [
        "xxx.xxxx.google..."
      ]
    },
    "activity": {
      "type": "string",
      "description": "(Android only) Start point of android app for mobile testing.",
      "examples": [
        "xxx.xxx.xxx.xxx.twint..."
      ]
    },
    "seriesNumber": {
      "type": "string",
      "description": "Test Series number for execution sequence of test case with meta",
      "examples": [
        "seriesNumber:suite.1.case.01",
        "seriesNumber:suite.1.case.02"
      ]
    },
    "story": {
      "type": "string",
      "description": "Story description of the test case.",
      "examples": [
        "User tries to login the system with invalid username and invalid password."
      ]
    },
    "epic": {
      "type": "string",
      "description": "Epic description of the test case.",
      "examples": [
        "Login Tests Epic."
      ]
    },
    "feature": {
      "type": "string",
      "description": "Feature description of the test case.",
      "examples": [
        "Invalid Login Features."
      ]
    },
    "startURL": {
      "type": "string",
      "description": "Start url for the test object.",
      "examples": [
        "https://www.myPage.com/login"
      ]
    },
    "steps": {
      "type": "array",
      "description": "Test Case Steps",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Test step name that implemented in java method with annotation like @TestStep(name=\"my Step\")."
          },
          "testObject": {
            "type": "string",
            "description": "Test page object name that implemented in java class with annotation like @TestObject(name=\"my Step\")."
          },
          "using": {
            "type": "string",
            "description": "To override the method definition of parameters in annotation like @TestStep(using=\"myData.user\")."
          },
          "comment": {
            "type": "string",
            "description": "Comment for additional step info as such special identifier usefully for report"
          },
          "takeScreenshot": {
            "type": "boolean",
            "enum": [
              true,
              false
            ],
            "description": "To specify the screen shot taken strategy only for the step."
          },
          "stopOnError": {
            "type": "boolean",
            "enum": [
              true,
              false
            ],
            "description": "To specify the stop on error strategy only for the step."
          }
        },
        "required": [
          "name",
          "testObject"
        ]
      }
    }
  },
  "required": [
    "meta",
    "name",
    "type",
    "description",
    "screenshotLevel",
    "testDataRef",
    "steps"
  ]
}

=== sleod/tas-framework-lite/target/classes/testCases/testSetMobile/Demo_Android.json
{
  "meta": [
    "@focusAndroid"
  ],
  "name": "Demo Android Try",
  "type": "mobile_android",
  "description": "Demo Test Case of android twint",
  "source": "TFS",
  "testCaseId": "",
  "requirement": "",
  "reference": "",
  "screenshotLevel": "ERROR",
  "testDataRef": "File:testData/google-testData.json",
  "appName": "ch.raiffeisen.twint",
  "activity": "",
  "steps": [
    {
      "name": "type login name",
      "testObject": "android login page"
    }
  ]
}

=== sleod/tas-framework-lite/src/main/resources/testCases/testDemo/testDemo.json
{
  "meta": [
    "@testDemo"
  ],
  "name": "Demo Test",
  "type": "web_app",
  "description": "Demo Test Case",
  "source": "TFS",
  "testCaseId": "",
  "requirement": "",
  "reference": "",
  "screenshotLevel": "ERROR",
  "testDataRef": "File:google-testData.json",
  "startURL": "https://formstone.it/components/dropdown/demo/",
  "seriesNumber": "",
  "steps": [
    {
      "name": "Test Demo",
      "testObject": "Demo Page"
    }
  ]
}

=== sleod/tas-framework-lite/src/main/resources/testCases/testSet1/GoogleDemo6.json
{
  "meta": [
    "@nightly",
    "@CI",
    "@demo",
    "@demo6"
  ],
  "name": "Google Demo Test Case 6",
  "type": "web_app",
  "description": "Demo Test Case of Google home page 6",
  "source": "TFS",
  "testCaseId": "",
  "requirement": "",
  "reference": "",
  "screenshotLevel": "ERROR",
  "testDataRef": "File:testData/google-testData.json",
  "startURL": "https://www.google.de",
  "seriesNumber": "",
  "steps": [
    {
      "name": "Check Fields Presents",
      "testObject": "Google Home Page"
    },
    {
      "name": "Search Text",
      "testObject": "Google Home Page"
    },
    {
      "name": "Check First Entry of Search Result",
      "testObject": "Search Result Page"
    },
    {
      "name": "Search Text Twice",
      "testObject": "Google Home Page"
    }
  ]
}

=== sleod/tas-framework-lite/src/main/resources/testCases/testSetGoogle/Demo6.json
{
  "meta": [
    "@demo1.6",
    "@all"
  ],
  "name": "Google Demo Test Case 6",
  "type": "web_app",
  "description": "Demo Test Case 6 with GlobalTestData File",
  "source": "TFS",
  "testCaseId": "",
  "requirement": "",
  "reference": "",
  "screenshotLevel": "ERROR",
  "testDataRef": "File:testData/google-testData.json",
  "startURL": "https://www.google.ch",
  "steps": [
    {
      "name": "Check Fields Present",
      "testObject": "Google Home Page"
    },
    {
      "name": "Global Search Text",
      "testObject": "Google Home Page",
      "comment": "Die Daten werden aus der File demo-testdata-global.json gelesen"
    },
    {
      "name": "Search Text",
      "testObject": "Google Home Page"
    }
  ]
}

=== sleod/tas-framework-lite/src/main/resources/testCases/testSet1/GoogleDemo2.json
{
  "meta": [
    "@nightly",
    "@CI",
    "@demo2",
    "@demo23"
  ],
  "name": "Google Demo Test Case 2",
  "type": "web_app",
  "description": "Demo Test Case of Google home page 2",
  "source": "TFS",
  "testCaseId": "",
  "requirement": "",
  "reference": "",
  "screenshotLevel": "ERROR",
  "testDataRef": "File:google-testData.json",
  "startURL": "https://www.google.ch",
  "seriesNumber": "",
  "steps": [
    {
      "name": "Check Fields Present",
      "testObject": "Google Home Page"
    },
    {
      "name": "Check Page Title",
      "testObject": "Google Home Page",
      "using": "pageTitle1"
    },
    {
      "name": "Search Text",
      "testObject": "Google Home Page"
    },
    {
      "name": "Check First Entry of Search Result",
      "testObject": "Search Result Page"
    },
    {
      "name": "Search Text Twice",
      "testObject": "Google Home Page"
    },
    {
      "name": "Search Text Triple",
      "testObject": "Google Home Page"
    },
    {
      "name": "Search List",
      "testObject": "Google Home Page"
    }
  ]
}

=== sleod/tas-framework-lite/src/main/resources/testCases/testSetGoogle/Demo4.json
{
  "meta": [
    "@demo1.4",
    "@all"
  ],
  "name": "Google Demo Test Case 4",
  "type": "web_app",
  "description": "Demo Test Case 4 with Check search with map",
  "source": "TFS",
  "testCaseId": "",
  "requirement": "",
  "reference": "",
  "screenshotLevel": "ERROR",
  "testDataRef": "File:testData/google-testData.json",
  "startURL": "https://www.google.ch",
  "steps": [
    {
      "name": "Check Fields Present",
      "testObject": "Google Home Page"
    },
    {
      "name": "Check Page Title ää",
      "testObject": "Google Home Page",
      "comment": "Das ist ein Kommentar"
    },
    {
      "name": "Search Text",
      "testObject": "Google Home Page"
    },
    {
      "name": "Check Fields Present",
      "testObject": "Search Result Page"
    },
    {
      "name": "Check First Entry of Search Result",
      "testObject": "Search Result Page",
      "using": "searchResultEntry"
    },
    {
      "name": "Check search with map",
      "testObject": "Search Result Page"
    }
  ]
}

=== sleod/tas-framework-lite/target/classes/testCases/testSetMobile/Demo_IOS.json
{
  "meta": [
    "@focusIOS"
  ],
  "name": "Demo IOS Try",
  "type": "mobile_ios",
  "description": "Demo Test Case of ios twint",
  "source": "TFS",
  "testCaseId": "",
  "requirement": "",
  "reference": "",
  "screenshotLevel": "ERROR",
  "testDataRef": "File:testData/google-testData.json",
  "appName": "ch.raiffeisen.twint",
  "steps": [
    {
      "name": "Check Fields Present",
      "testObject": "ios login page"
    }
  ]
}

=== sleod/tas-framework-lite/src/main/resources/testCases/testSet2/Demo1.json
{
  "meta": [
    "@remote",
    "@nightly",
    "@CI"
  ],
  "name": "Demo test 1",
  "type": "mobile_web_app",
  "description": "Demo Test Case of Google home page",
  "source": "TFS",
  "testCaseId": "",
  "requirement": "",
  "reference": "",
  "screenshotLevel": "ERROR",
  "testDataRef": "File:testData/google-testData.csv",
  "startURL": "https://www.google.ch",
  "steps": [
    {
      "name": "Check Fields Presents",
      "testObject": "Google Home Page"
    },
    {
      "name": "Check Page Title",
      "testObject": "Google Home Page"
    },
    {
      "name": "Search Text",
      "testObject": "Google Home Page"
    },
    {
      "name": "Check Fields Presents",
      "testObject": "Search Result Page"
    },
    {
      "name": "Check First Entry of Search Result",
      "testObject": "Search Result Page",
      "using": "searchResultEntry1"
    },
    {
      "name": "Check search with map",
      "testObject": "Search Result Page"
    }
  ]
}
